'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reports
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''sitename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitename As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''logout_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logout_btn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''homebtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents homebtn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chk_selectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_selectAll As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''selectedSiteConcept_holder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedSiteConcept_holder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''selectAllSiteConcept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectAllSiteConcept As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_siteConcept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_siteConcept As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''selected_holder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selected_holder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''selectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectAll As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_list As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''date_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents date_from As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''date_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents date_to As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''search_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_btn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Exportbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Exportbtn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chk_withZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_withZero As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''selected_holder_brands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selected_holder_brands As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SelectAllBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectAllBrand As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_brand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_brand As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''backgrounddiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents backgrounddiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''deleted_items_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deleted_items_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''selectedDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedDocument As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btn_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''datacounter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datacounter As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''deletedItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deletedItems As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''dg_result control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dg_result As Global.System.Web.UI.WebControls.GridView
End Class
